name: Cranberry - DMP 2024 Project
description: Cranberry project for Dedicated Mentoring Program (DMP) 2024 
title: "[DMP 2024]: "
labels: ["DMP 2024"]
body:
  - type: textarea
    id: ticket-description
    validations:
      required: true
    attributes:
      label: Ticket Contents
      value: |
        ## Description
        [Berry Wiki Women’s Health (A UX Project)]

  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals & Mid-Point Milestone
      Description: |
      Berry Wiki is a women’s health wiki with information in the form of audio, video, and text designed for the women of today. 
      At Cranberry, we believe there is a big gap between what women seek and the information available online. More importantly, we see that the information available online needs to be contextualized to India. We have a team of researchers who create and contextualize information to train our chatbot, Berry. We intend to make this information open source. Berry Wiki will provide women’s health, specifically preventive health-related information in a simple, easy-to-understand, intuitive-to-navigate way. 
      The scope of the project is ONLY UX and not the tech backend. We currently use wix.com for hosting our side, happy to use another provider. One of the sites that comes closest to our vision is https://helloclue.com/articles
      But we believe it is not designed for how a user might want to navigate information especially when they are seeking answers for a specific question like “Is my period late?”, “Do I have heavy bleeding?”
      value: |
        ## Goals
        - [ ] Set up the design objective & user persona
        - [ ] Conduct user interviews to generate insights on online content consumption
        - [ ] Create at least 3 mock design mocks to test assumptions
        - [ ] Conduct User Testing on the mocks
        - [ ] Define the elements/blocks of Berry WIki

  - type: textarea
    id: ticket-setup
    attributes:
      label: Setup/Installation 
      description: You can check out our current Information protocols at https://cranberryfit.notion.site/Dysmenorrhea-OR-Period-Pain-b4670a2074b0469296a2df1fc6715ed8?pvs=4, https://www.youtube.com/@cranberryforher & https://drive.google.com/drive/folders/1FBNr0eB1-HNNN58nq0WTzQwYRYE9PiLw?usp=drive_link - which give a sense of the information we want to put out there.

  - type: textarea
    id: ticket-expected-outcome
    attributes:
      label: Expected Outcome
      description: A website hosted on https://www.cranberry.fit/. The website is primarily structured with a content-first approach (maybe video first?)  Women can navigate through the site easily and find answers to their questions. The scope looks design of the structure of information, navigation, icons/design choices required to create a good reading/learning experience, and colours (optional)
      Note: We looked into the current wiki structures of GitBooks, MediaWiki, and other similar sites. They are optimized for navigation for an engineer-first person and tech documentation. For health documentation, we find good examples in Healthline, we need to create an Indian version of the same. 


  - type: textarea
    id: ticket-acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specific criteria to be created in collaboration with the mentors as user interviews will throw more light into what women are exactly looking for when seeking information. The quick summary is here
                    - Women can navigate with ease through the landing page
                    - Women can find answers to the questions they are looking for
                    - Women can share information if required


  - type: textarea
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: NA.

  - type: textarea
    id: ticket-mockups
    attributes:
      label: Mockups/Wireframes
      description: Include links to any visual aids, mockups, wireframes, or diagrams that help illustrate what To be created as a part of the project. Relevant sites are added above.

  - type: input
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: Berry Wiki
    validations:
      required: true

  - type: dropdown
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: Empower Digital Health / Cranberry
      multiple: false
      options:
        - Bandhu
        - Blockster Global (CREDBEL)
        - Civis
        - Dhwani
        - Dhiway
        - EGov
        - EkShop Marketplace
        - FIDE
        - If Me
        - Key Education Foundation
        - Norwegian Meteorological Institute
        - Planet Read
        - Project Second Chance
        - Reap Benefit
        - SamagraX
        - ShikshaLokam
        - Tech4Dev
        - Tekdi
        - The Mifos Initiative
        - Tibil
        - Ushahidi
        - Arghyam
        - Piramal Swasthya Management Research Institute
    validations:
      required: true

  - type: dropdown
    id: ticket-governance-domain
    attributes:
      label: Domain
      options:
        - ⁠HealthTech 
        - Media
    validations:
      required: true


  - type: dropdown
    id: ticket-technical-skills-required
    attributes:
      label: Tech Skills Needed
      description: Select the technologies needed for this ticket (use Ctrl or Command to select multiple)
      multiple: true
      options:
        - UX
        - User Experience
        - User Interviews
        - Mock Design
        - Wireframes
    validations:
      required: true

  - type: textarea
    id: ticket-mentors
    attributes:
      label: Mentor(s)
      description: Saraswati, Aditi, Treemouse
    validations:
      required: true

  - type: dropdown
    id: ticket-category
    attributes: 
      label: Category
      description: Choose the categories that best describe your ticket
      multiple: true
      options:
        - UX Design
    validations:
      required: true

  
